### ISSUE TITLE
Always `title` should be set for Hist. 

### ISSUE THREAD

**Issue by ChanchalKumarMaji** [henryiii/mini_hist#11]
@henryiii 
https://github.com/henryiii/mini_hist/blob/8b51bb28529859ff99e743b1591eb7b0210f4c2b/tests/test_general.py#L5
Here, this should raise an Error. It should be - 
`h = Hist(axis.Regular(10, 0, 1, title="x [units]"))`. Title should always be set when using Hist.

**Comment by henryiii** [comment]
The NamedHist requires all axis have names. Titles are always optional (only for plotting), and currently names are optional when not using a NamedHist.

PS: A name is a valid identifier, while a title can be anything, including having spaces, etc.
