### ISSUE TITLE
Method name error

### ISSUE THREAD

**Issue by LovelyBuggies** [henryiii/mini_hist#12]
@henryiii Henry, when I try the following snippet, an error is raised: **"TypeError: 'str' object is not callable"**.

```python
bl = hist.axis.Regular(10, 0, 1,name="valid")
print(bl.name("invalid"))
```

With the errors of getting and setting names, it seems `test_named.py` need some supplementation.

**Comment by LovelyBuggies** [comment]
More specifically, I think `test_name.py` should add lines like this and be passed:

```python
h = NamedHist(axis.Regular(10, 0, 1, name="x"))
h.fill(x=[0.35, 0.35, 0.45])

assert h.name() == x
assert h.name("xx").name() == xx

h = NamedHist(axis.Regular(20, -1, 1, name="x"), axis.Regular(10, 0, 1, name="y"))
h.fill(x=[0.35, 0.35, 0.45], y=[0.35, 0.35, 0.45])

assert h["x"].name() == x
assert h["y"].name() == y
assert h["x"].name("xx").name() == xx
assert h["y"].name("yy").name() == yy
```

**Comment by ChanchalKumarMaji** [comment]
@LovelyBuggies @henryiii 
I think this should pass - 
```python
h = NamedHist(
    axis.Regular(20, -1, 1, name="x"),
    axis.Regular(10, 0, 1, name="y"),
)

h.fill(x=[0.35, 0.35, 0.45], y=[0.35, 0.35, 0.45])
    
assert h[13, 3] == 2
assert h[14, 4] == 1

assert h[{'x':13, 'y':3}] == 2
assert h[{'x':14, 'y':4}] == 1
```

**Comment by LovelyBuggies** [comment]
Yep, I know that the codes above should work (*last 2 lines after boost-hist 0.7.0*). What I want to ask is that the `name()` (both set and get) method doesn't seem to work like this way.

```python
print(h.axes[0].name())     # method should work but not, where type(h.axes[0]) == hist._internal.axis.Regular
print(h.axes[0].name("new_name"))     # method should work but not, where type(h.axes[0]) == hist._internal.axis.Regular
# directly obtain attribute name, h.axes[0].name works
```

This indicates that your `name()` method of the Regular classes may be problematic.

**Comment by ChanchalKumarMaji** [comment]
`name` is a property. It should be accessed like `h.axes[0].name`.

**Comment by LovelyBuggies** [comment]
But how to reset the name for an axis?

**Comment by LovelyBuggies** [comment]
For the Regular axis, there is no regular key-swapping operations (e.g. pop) for metadata dict in func `name(val)`.

**Comment by ChanchalKumarMaji** [comment]
For resetting, `h.axes[0].name = "x"`.

**Comment by LovelyBuggies** [comment]
Thanks! So what is the use of `name` and `name(val)` in `Regular` class?

**Comment by henryiii** [comment]
```python
bl = hist.axis.Regular(10, 0, 1, name="valid")
bl.name = "invalid"
print(bl.name)
```

Should print out "invalid". I rather think we should not allow names to be changed, however, since that adds a complicated check; you have to make sure names do not match inside a histogram. So this would be hard to protect against if you allow names to be changed:

```python

h = hist.NamedHist(
    hist.axis.Regular(10, 0, 1, name="x"),
    hist.axis.Regular(10, 0, 1, name="y"),
)

x_ax, y_ax = h.axes
y_ax.name = "x" # Oops, now can't fill, etc!
```
