### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by LovelyBuggies** [henryiii/mini_hist#2]
@henryiii Hi Henry, I think students should be able to run codes successfully before `#Hypothetical Hist`. But it seems like pure boost-hist has something wrong.

```python
valid_only = h[:, :, bh.loc(True)] # Passing True directly happens to work here as well
valid_only = h[{2:bh.loc(True)}]   # Alternate way to do the same thing
```

When running the code above, an error was thrown out:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-1-7548476a3be9> in <module>
     20 
     21 valid_only = h[:, :, bh.loc(True)] # Passing True directly happens to work here as well
---> 22 valid_only = h[{2:bh.loc(True)}]   # Alternate way to do the same thing

/usr/local/lib/python3.7/site-packages/boost_histogram/_internal/hist.py in __getitem__(self, index)
    499             elif not isinstance(ind, slice):
    500                 raise IndexError(
--> 501                     "Must be a slice, an integer, or follow the locator protocol."
    502                 )
    503             if ind != slice(None):

IndexError: Must be a slice, an integer, or follow the locator protocol.
```

Is this normal? Is `valid_only = h[{2:bh.loc(True)}]` naturally something we should implement to achieve the hypothetical hist?

**Comment by LovelyBuggies** [comment]
Yep, now I am 80% sure that it's a bug in the method `__getitem__(self, index)` of class `Histogram` in boost-hist `internal/hist.py`.

**Comment by henryiii** [comment]
I am 98% sure this is a bug. I'll try to look into it soon.

**Comment by henryiii** [comment]
I've updated the README with something that should hopefully work now, and a mention of the bug in 0.6.2. I also have a PR that should fix the problem when 0.7.0 comes out. Thanks!!!

**Comment by LovelyBuggies** [comment]
Missing a ')' in `valid_and_invalid = h[{2:slice(None, None, bh.sum}]`.

**Comment by henryiii** [comment]
Thanks again!

**Comment by LovelyBuggies** [comment]
@henryiii  Note that `h[0][0][0]` is not supported by Boost-Histogram 0.6.2. Will statement `h[0][0][0]` work well for Hist-3D (`Regular()`-based) in Boost-Histogram 0.7.0?

**Comment by henryiii** [comment]
No, the correct syntax is `h[0,0,0]` (even in Numpy this is better). You can imitate this with `h[0, :, :][0, :][0]` but it's a bad idea, you will make three copies. Numpy avoids full copies by slicing tricks so it's not (as) bad.

**Comment by henryiii** [comment]
The bug fixed in the next version is that the `h[dict]` form *only* works with slices currently. It should behave like normal access and allow picking a single value.

**Comment by henryiii** [comment]
FYI, 0.7.0 is out both on PyPI and Conda-Forge.

**Comment by LovelyBuggies** [comment]
Have been done: update codes, notebooks, and tests.
