### ISSUE TITLE
Some Changes in Tests ?

### ISSUE THREAD

**Issue by ChanchalKumarMaji** [henryiii/mini_hist#3]
`test_named.py` is given as
```python
from hist import axis, NamedHist


def test_basic_usage():
    h = NamedHist(
        axis.Regular(10, 0, 1, name="x")
    )  # NamedHist should require axis.Regular to have a name set

    h.fill([0.35, 0.35, 0.45])  # Fill should be keyword only, with the names

    # Optional if you want these to fail
    assert h[2] == 0
    assert h[3] == 2
    assert h[4] == 1
    assert h[5] == 0

    # assert h[{'x':2}] # Should work
```

but it should be something like - 
```python
from hist import axis, NamedHist


def test_basic_usage():
    h = NamedHist(
        axis.Regular(10, 0, 1, name="x")
    )  # NamedHist should require axis.Regular to have a name set

    h.fill(x=[0.35, 0.35, 0.45])  # Fill should be keyword only, with the names

    # Optional if you want these to fail
    assert h[2] == 0
    assert h[3] == 2
    assert h[4] == 1
    assert h[5] == 0
    
    assert h[{'x':3}] # Should work
```
as `h.view()` gives - `[0. 0. 0. 2. 1. 0. 0. 0. 0. 0.]`, so - 
`h[{'x': 2}] gives 0.0` and `h[{'x': 3}] gives 2`. And assert of 0.0 gives Error. 

Am I correct ? @henryiii . Thank You.

**Comment by LovelyBuggies** [comment]
That's a feature we need to add, but for now, it doesn't work.

**Comment by ChanchalKumarMaji** [comment]
h[{'x': 2}] gives 0. So, assert of 0 gives error. But h[{'x': 3}] works fine as it gives 2.

**Comment by LovelyBuggies** [comment]
I think you might have a wrong understanding. 

> as `h.view()` gives - [0. 0. 0. 2. 1. 0. 0. 0. 0. 0.], so -
> `h[{'x': 2}]` gives 0.0 and `h[{'x': 3}]` gives 2. And assert of 0.0 gives Error.

The real meaning of this code is to assign value to the second bin in the axis named 'x'. 

Have you ever run this snippet?

```python
# Pure boost-histogram
import boost_histogram as bh

h = bh.Histogram(
    bh.axis.Regular(10, -1, 1, metadata={'name':'x'}),
    bh.axis.Regular(10, -1, 1, metadata={'name':'y'}),
    bh.axis.Integer(0, 2, underflow=False, overflow=False, metadata={'name':'valid'}),
)

h.fill(x, y, valid)

valid_only = h[:, :, bh.loc(True)] # Passing True directly happens to work here as well
valid_only = h[{2:bh.loc(True)}]   # Alternate way to do the same thing ### BROKEN in 0.6.2
```

This is "broken in 0.6.2", meaning that we can not get the ideal results for now.

**Comment by ChanchalKumarMaji** [comment]
Yes, I cloned the new PR which resolves this. So, the above code works perfectly in my system.

**Comment by LovelyBuggies** [comment]
Yeah, this was quite confusing at first but I figured it out. For example, in a 3-D hist, if you set two Regular axes (x, y) and a Bool axis (z), the meaning of `valid_only = h[:, :, bh.loc(True)]` is to assign value to the bins covering all x and y but having z is true (of course at present this is represented as 1-2 on Integer axis).

**Comment by henryiii** [comment]
The named access `h[{'x':3}]` is exactly the same as the positional access `h[3]`, this means the `== 2` was accidentally deleted by me when I was adding the comment. It was supposed to be 2. And yes, it's a feature to add, but sadly it's missing a comparison so it can't just be uncommented as is.

By the way, minor point for @LovelyBuggies: *assign* means you are changing the values. So `h[:, :, bh.loc(True)] = 0` would assign 0 to all then bins where valid is True, and would not touch the bins where valid is False. I think you mean *access*.

**Comment by henryiii** [comment]
I've updated the tests to make the uncommentable test clearer. Thank you!
