### ISSUE TITLE
Fatal: import Hist failure

### ISSUE THREAD

**Issue by LovelyBuggies** [henryiii/mini_hist#4]
@henryiii It seems that hist module cannot found:

- Importing hist module failure in notebooks after `pip3 install hist` (pip globally and try globally).
- Test the template fail.

```bash
============================= test session starts ==============================
platform darwin -- Python 3.7.0, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /Users/nino/Documents/GitHub/Nino-Hist
collected 0 items / 3 errors                                                   

==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_basic.py _____________________
ImportError while importing test module '/Users/nino/Documents/GitHub/Nino-Hist/tests/test_basic.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_basic.py:1: in <module>
    import hist
E   ModuleNotFoundError: No module named 'hist'
```

**Comment by henryiii** [comment]
Did you install it following the instructions on the README? If you have activated the virtual environment, you should be able to run it.

**Comment by LovelyBuggies** [comment]
Yes, step by step. 

```bash
python3 -m venv .env            # Make a new environment in ./.env/
source .env/bin/activate        # Use the new environment
pip3 install -r requirements.txt # Install the package requirements
python3 -m pytest tests  # Test
```

**Comment by henryiii** [comment]
Oops, did you run `pip install -e .`?

(note that after you activate the environment, you don't need the 3's anymore, but they don't hurt either)

**Comment by LovelyBuggies** [comment]
Thanks, but I met another error when `pip install -e .`: 

```bash
File "/Users/nino/Documents/GitHub/Nino-Hist/src/hist/__init__.py", line 7, in <module>
        from .version import version as __version__
    ModuleNotFoundError: No module named 'hist.version'
```

**Comment by LovelyBuggies** [comment]
Hint: I did not have `version.py` in `src/hist`, but in `pyproject.toml`, 

```
[tool.setuptools_scm]
write_to = "src/hist/version.py"
```

Why did that happen?

**Comment by henryiii** [comment]
That gets generated when you build, but you need a recent version of setuptools (42 or better). What version of pip do you have? pip 10+ is supposed to install setuptools for you.

**Comment by LovelyBuggies** [comment]
Find the problem. The initialized virtual environment has pip version 10.0.1, which has the finding version issue. After upgrading, all things run well!

**Comment by LovelyBuggies** [comment]
Thanks a lot~
