### ISSUE TITLE
Issue in Plot Scale and github Cloud [Continuous Integration] Testing ! 

### ISSUE THREAD

**Issue by ChanchalKumarMaji** [henryiii/mini_hist#8]
@henryiii I am getting a plot like [this](https://github.com/ChanchalKumarMaji/dataset/blob/master/index.png). I am plotting the `values` but I think the `Counts` axis in my plot is 10 times smaller than what is shown in the given sample diagram. 
Also, can you please tell me how to add those rectangular patches. :thinking: . Thank You.

**Comment by ChanchalKumarMaji** [comment]
Another problem is `travis` does not install matplotlib, don't know why. So, errors are there in the cloud testing. Any suggestions ? Thank You.

**Comment by henryiii** [comment]
First question: I don't think the scale is important, it was just a very simple example of what you might expect to make. I could have had 10x more data when I made the plot ( I was fiddling with the data size while making it for debugging). You don't need to match it perfectly. Or even very close; it's just a guide.

The patches were with rect = matplotlib.patches.Rectangle, using ax.add_patch(rect) or something like that, going from memory. I also used a blended coordinate transform for it (y axis from data coordinates, x axis from plot coordinates). I have a hint in the readme similar to what I just said. Mostly I just did lots of googles of the Matplotlib documentation and followed examples there.

**Comment by henryiii** [comment]
Here, I only install the test requirements (I don't install requirements.txt):

https://github.com/henryiii/mini_hist/blob/08ba9e7785abf36f2e8c1e4dc565d142df63e3f7/.github/workflows/ci.yml#L40

And, here, I only include Matplotlib in the dev and mil requirements, not test:

https://github.com/henryiii/mini_hist/blob/08ba9e7785abf36f2e8c1e4dc565d142df63e3f7/setup.cfg#L43-L49

Either add matplotilb to test, add dev or mpl to the CI (`[test,dev]`), or add a `python -m pip install -r requirements.txt` to the CI.

**Comment by henryiii** [comment]
Yes, I'm 100% sure there are more than 1,000 data points in the histogram I've plotted - some bins have nearly 500 alone. :)

**Comment by ChanchalKumarMaji** [comment]
Thank You ! :smiley:

**Comment by ChanchalKumarMaji** [comment]
> First question: I don't think the scale is important, it was just a very simple example of what you might expect to make. I could have had 10x more data when I made the plot ( I was fiddling with the data size while making it for debugging). You don't need to match it perfectly. Or even very close; it's just a guide.
> 
> The patches were with rect = matplotlib.patches.Rectangle, using ax.add_patch(rect) or something like that, going from memory. I also used a blended coordinate transform for it (y axis from data coordinates, x axis from plot coordinates). I have a hint in the readme similar to what I just said. Mostly I just did lots of googles of the Matplotlib documentation and followed examples there.

Also, for this `pull_plot` will `sigma` be always equal to 1 ? If not, how can we get `sigma` from the histogram object ? Otherwise, I think we have to pass sigma used in `np.random.normal()` as a parameter to the `pull_plot` function. I think the `sigma` value is important for adding the rectangular patches.

**Comment by henryiii** [comment]
This is largely why I chose the simplest case for the evaluation task, to avoid extra real-world complications. However, I think we can always compute sigma for a histogram bin, either using sqrt(counts) or the variance found in the fancier storages.
