### ISSUE TITLE
Who has the fill()?

### ISSUE THREAD

**Issue by LovelyBuggies** [henryiii/mini_hist#9]
For project 1, I derived my class upon boost-histogram `Regular()`. But when I tried to use `self.axes[index].fill(value)` in my class, an error thrown: `AttributeError: 'Regular' object has no attribute 'fill'`. I know that the `Regular()` object shouldn't have `fill()`, but how can I access the variable named `_hist` in my subclass?

**Comment by LovelyBuggies** [comment]
Maybe types like this can `fill()`:

```python
_histograms = (
    _core.hist.any_double,
    _core.hist.any_int64,
    _core.hist.any_atomic_int64,
    _core.hist.any_unlimited,
    _core.hist.any_weight,
    _core.hist.any_mean,
    _core.hist.any_weighted_mean,
)
```

But how could I access it in the library `Hist`?

**Comment by ChanchalKumarMaji** [comment]
I think this is the task you have to do. By doing this you have to explore the full `boost_histogram` package.

**Comment by henryiii** [comment]
You can only fill bh.Histogram (or something that inherits from it, like Hist or NamedHist). You can't fill an Axis. They don't have any storage - they just represent how data coordinates turn into bin coordinates.

**Comment by LovelyBuggies** [comment]
Solved, using some tricks 😝. Things more like Python rather than BH.
